In [2]:
import torch
import numpy as np

@[TOC]

## **gather**
- torch.gather(tensor, dim, index)     
- tensor.gather(dim, index)

从dim的维度按照相应的顺序来取tensor中的index位置的值

In [12]:
example = torch.Tensor([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 8]])
index = torch.LongTensor([[2, 1, 0]])

当dim为0时，index作用在行上(此时要求index的列维度等于example行维度)，列一次累加最后输出的结果为：
$\begin{bmatrix}{example[\textbf 2][0] \\ example[\textbf 1][1] \\ exmaple[\textbf 0][2]} \end{bmatrix}$

In [13]:
example.gather(0, index)

tensor([[7., 5., 3.]])

当dim为1的时候，index作用在列上(此时要求index的行维度等于example列维度)，结果为$\begin{bmatrix}{example[0][\textbf 2] \\ example[1][\textbf 1] \\ exmaple[2][\textbf 0]} \end{bmatrix}$

In [17]:
example.gather(1, index.t())

tensor([[3.],
        [5.],
        [7.]])

## **argmax**

argmax获取最大值的索引
- torch.argmax(tensor, dim=None)

In [5]:
example = torch.tensor([[1, 4, 5], [6, 2, 6], [7, 8, 0]])

不指定dim时，返回tensor最大值按顺序数的index

In [6]:
torch.argmax(example)

tensor(7)

指定dim时返回该dim上的index

In [7]:
torch.argmax(example, 1)

tensor([2, 2, 1])