# **1 tf.data基础api**

In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn 
import pandas as pd
import os, gc, sys, time
import tensorflow as tf
from tensorflow import keras

import warnings
warnings.filterwarnings('ignore')

## **1.1 from_tensor_slices**

In [2]:
dataset = tf.data.Dataset.from_tensor_slices(np.arange(10))
print(dataset)

<TensorSliceDataset shapes: (), types: tf.int32>


In [3]:
for item in dataset:
    print(item, end='\t')

tf.Tensor(0, shape=(), dtype=int32)	tf.Tensor(1, shape=(), dtype=int32)	tf.Tensor(2, shape=(), dtype=int32)	tf.Tensor(3, shape=(), dtype=int32)	tf.Tensor(4, shape=(), dtype=int32)	tf.Tensor(5, shape=(), dtype=int32)	tf.Tensor(6, shape=(), dtype=int32)	tf.Tensor(7, shape=(), dtype=int32)	tf.Tensor(8, shape=(), dtype=int32)	tf.Tensor(9, shape=(), dtype=int32)	

## **1.2 基本操作**

**repeat epoch**

In [4]:
dataset = dataset.repeat(3) # 参数表示重复多少次，没有传入的话表示重复无限次

**get batch**

In [5]:
dataset = dataset.batch(7) # 参数表示batch_size的大小

In [6]:
for item in dataset:
    print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


**interleave:对数据集中的每个数据进行处理, 将变换后的数据合并形成一个新的数据集**      
> 当你的dataset是文件名的时候，可以使用interleave来读取数据形成新的dataset

In [9]:
dataset2 = dataset.interleave(
    lambda x : tf.data.Dataset.from_tensor_slices(x), # map_fnb表示函数
    cycle_length = 5, # 并行数opt
    block_length = 5 # 每个输入产生的连续元素数量opt
)
    
for item in dataset2:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype

## **1.3 多个数据的处理**

In [12]:
x = np.array([[1, 2], [2, 3], [3, 4]])
y = np.array([0, 1, 3])
dataset3 = tf.data.Dataset.from_tensor_slices((x, y))
for item in dataset3:
    print(item)

(<tf.Tensor: id=98, shape=(2,), dtype=int32, numpy=array([1, 2])>, <tf.Tensor: id=99, shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: id=100, shape=(2,), dtype=int32, numpy=array([2, 3])>, <tf.Tensor: id=101, shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: id=102, shape=(2,), dtype=int32, numpy=array([3, 4])>, <tf.Tensor: id=103, shape=(), dtype=int32, numpy=3>)


In [13]:
x = np.array([[1, 2], [2, 3], [3, 4]])
y = np.array([0, 1, 3])
dataset3 = tf.data.Dataset.from_tensor_slices({'features':x, 'labels':y})
for item in dataset3:
    print(item)

{'features': <tf.Tensor: id=112, shape=(2,), dtype=int32, numpy=array([1, 2])>, 'labels': <tf.Tensor: id=113, shape=(), dtype=int32, numpy=0>}
{'features': <tf.Tensor: id=114, shape=(2,), dtype=int32, numpy=array([2, 3])>, 'labels': <tf.Tensor: id=115, shape=(), dtype=int32, numpy=1>}
{'features': <tf.Tensor: id=116, shape=(2,), dtype=int32, numpy=array([3, 4])>, 'labels': <tf.Tensor: id=117, shape=(), dtype=int32, numpy=3>}
