# **使用GPU计算**

In [2]:
# 查看显卡信息
!nvidia-smi

Wed Oct 23 10:38:46 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 431.60       Driver Version: 431.60       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060   WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   39C    P8     2W /  N/A |    330MiB /  6144MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [3]:
import torch
import torch.nn as nn

In [4]:
# 检查GPU是否可用
torch.cuda.is_available()

True

In [5]:
# 查看GPU数量
torch.cuda.device_count()

1

In [6]:
# 查看GPU名称
torch.cuda.get_device_name()

'GeForce GTX 1060'

## **Tensor的GPU计算**

默认情况是把Tensor存储在内存上的，只有显式指定存储设备，Tensor才会在GPU上计算

In [8]:
# 方法1
x = torch.randn((3, 3)).cuda(0)
x

tensor([[ 0.9957,  2.1639, -0.0369],
        [ 1.3753, -2.0544,  0.4818],
        [ 1.3340, -0.1558,  1.0577]], device='cuda:0')

In [9]:
# 方法2
device = torch.device('cuda')
x = torch.tensor([1, 2, 3], device=device)
x

tensor([1, 2, 3], device='cuda:0')

存储在GPU上的Tensor计算出来的Tensor还是存储在GPU上

In [10]:
y = x**2
y

tensor([1, 4, 9], device='cuda:0')

> 存储在cpu上的tensor无法和存储在GPU上的tensor进行计算！！！！！！

## **模型在GPU上计算**

In [14]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

可以将模型从CPU转换到GPU上来

In [15]:
net = net.cuda(0)
list(net.parameters())[0].device

device(type='cuda', index=0)

In [16]:
x = torch.rand(2,3).cuda()
net(x)

tensor([[0.0287],
        [0.0473]], device='cuda:0', grad_fn=<AddmmBackward>)

** 自定义模型**

In [17]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(4, 3)
        self.relu = nn.ReLU()
        self.output = nn.Linear(3, 1)
    
    def forward(self, x):
        hidden = self.hidden(x)
        return self.output(self.relu(hidden))

In [20]:
net = MLP()
list(net.parameters())[0].device

device(type='cpu')

In [21]:
net = net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)