# **池化**

**池化**的时机目的是**缓解卷积层对位置的过度敏感性**
卷积对位置过度敏感了，在后续的模式识别上可能造成不便，因为在实际的图片中，我们所有的样本感兴趣的物体不会再同样的位置，    
同一个的边缘对应的输出可能出现在卷积输出Y的不同位置

## **池化的方式**

- 最大池化
- 平均池化

In [1]:
import torch
from torch import nn

def pool2d(X, pool_size, mode='max'):
    X = X.float()
    p_h, p_w = pool_size
    Y = torch.zeros(X.shape[0] - p_h + 1, X.shape[1] - p_w + 1)
    for i in range(Y.shape[1]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i : i + p_h, j : j + p_w].max()
            if mode == 'avg':
                Y[i, j] = X[i : i + p_h, j : j + p_w].mean()
    return Y

In [2]:
X = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

## **padding&strides**

In [3]:
# 构造一个(1, 1, 4, 4)的矩阵作为输入
X = torch.arange(16, dtype=torch.float).view((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

torch.nn.MaxPool2d(kernel_size, stride=None, padding=0, dilation=1, return_indices=False, ceil_mode=False)

[参考连接](https://pytorch.org/docs/stable/nn.html#torch.nn.MaxPool1d)

In [5]:
maxpool2d = nn.MaxPool2d(3, padding=1, stride=2)
maxpool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [6]:
maxpool2d = nn.MaxPool2d((4, 2), padding=(2, 1), stride=(3, 2))
maxpool2d(X)

tensor([[[[ 4.,  6.,  7.],
          [12., 14., 15.]]]])

## ** 多通道**

In [7]:
X = torch.cat((X, X + 1), dim=1)

In [8]:
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [9]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])