In [6]:
import torch
import numpy as np

### 创建张量    
*********

创建5*3没有初始化的tensor

In [2]:
torch.empty(5, 3)

tensor([[1.0194e-38, 1.0469e-38, 1.0010e-38],
        [8.9081e-39, 8.9082e-39, 5.9694e-39],
        [8.9082e-39, 1.0194e-38, 9.1837e-39],
        [4.6837e-39, 9.2755e-39, 1.0837e-38],
        [8.4490e-39, 1.0286e-38, 1.0286e-38]])

创建5*3随机的Tensor

In [5]:
torch.rand(5, 3)

tensor([[0.1664, 0.9435, 0.7369],
        [0.4486, 0.1930, 0.0299],
        [0.4682, 0.1836, 0.5906],
        [0.1048, 0.7572, 0.3580],
        [0.3098, 0.8637, 0.8949]])

按照具体数据创建tensor

In [7]:
a = np.array([[1, 2], [3, 4]])

In [8]:
torch.tensor(a)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

创建各种指定数据和形状的tensor

In [12]:
b = torch.tensor(a)

In [13]:
torch.ones_like(b)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [18]:
torch.randn_like(b, dtype=torch.float)

tensor([[ 1.2864, -1.8640],
        [-1.1211, -0.7994]])

[官方api](https://pytorch.org/docs/stable/tensors.html)

### Tensor操作    
*********

加法

In [24]:
x = torch.randn(5, 3)
y = torch.randn(5, 3)

In [25]:
x + y

tensor([[-0.7174, -0.0812, -0.8485],
        [-2.0435, -1.4847,  0.6182],
        [-1.8853, -1.2858,  0.9454],
        [-1.9016, -0.1499, -0.4962],
        [-1.6494,  0.1030, -1.4655]])

In [26]:
torch.add(x, y)

tensor([[-0.7174, -0.0812, -0.8485],
        [-2.0435, -1.4847,  0.6182],
        [-1.8853, -1.2858,  0.9454],
        [-1.9016, -0.1499, -0.4962],
        [-1.6494,  0.1030, -1.4655]])

In [27]:
x.add_(y)

tensor([[-0.7174, -0.0812, -0.8485],
        [-2.0435, -1.4847,  0.6182],
        [-1.8853, -1.2858,  0.9454],
        [-1.9016, -0.1499, -0.4962],
        [-1.6494,  0.1030, -1.4655]])

> x.add是inplace操作会直接改变x，torch中所有的inplace操作都需要在后面带上_

索引

In [29]:
x[0]

tensor([-0.7174, -0.0812, -0.8485])

In [31]:
x[:,1:3]

tensor([[-0.0812, -0.8485],
        [-1.4847,  0.6182],
        [-1.2858,  0.9454],
        [-0.1499, -0.4962],
        [ 0.1030, -1.4655]])

torch还提供了一些其他的索引方式,点[这里](https://pytorch.org/docs/stable/torch.html#torch.gather)

改变形状

In [33]:
x.view(15)

tensor([-0.7174, -0.0812, -0.8485, -2.0435, -1.4847,  0.6182, -1.8853, -1.2858,
         0.9454, -1.9016, -0.1499, -0.4962, -1.6494,  0.1030, -1.4655])

In [34]:
x.reshape(15)

tensor([-0.7174, -0.0812, -0.8485, -2.0435, -1.4847,  0.6182, -1.8853, -1.2858,
         0.9454, -1.9016, -0.1499, -0.4962, -1.6494,  0.1030, -1.4655])

view和原来的数据共享内存，reshape会创建一个副本，但是torch的reshape存在问题，推荐先clone再view

torh计算的广播机制

In [36]:
x

tensor([[-0.7174, -0.0812, -0.8485],
        [-2.0435, -1.4847,  0.6182],
        [-1.8853, -1.2858,  0.9454],
        [-1.9016, -0.1499, -0.4962],
        [-1.6494,  0.1030, -1.4655]])

In [37]:
x + 1

tensor([[ 0.2826,  0.9188,  0.1515],
        [-1.0435, -0.4847,  1.6182],
        [-0.8853, -0.2858,  1.9454],
        [-0.9016,  0.8501,  0.5038],
        [-0.6494,  1.1030, -0.4655]])

In [47]:
torch.zeros_like(x) + torch.tensor([1.0, 2.0, 3.0])

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])

和numpy数组的转换

In [48]:
x.numpy()

array([[-0.7174088 , -0.08117479, -0.8485023 ],
       [-2.0435138 , -1.4846777 ,  0.6182262 ],
       [-1.8853085 , -1.2857624 ,  0.9454102 ],
       [-1.9015758 , -0.1499399 , -0.49622726],
       [-1.649449  ,  0.10302889, -1.4655378 ]], dtype=float32)

In [49]:
torch.from_numpy(np.array([2, 5.0]))

tensor([2., 5.], dtype=torch.float64)

关于其他计算，看[这里](https://pytorch.org/docs/stable/torch.html#torch.bmm)

同时参考了[这里](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)