# **1 tensorflow基础API**

In [1]:
import numpy as np
import sklearn
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import os, sys, time, gc
import tensorflow as tf
from tensorflow import keras
import tensorflow.keras.backend as K

## **1.1 基础api**

**常量**`tf.constant`

In [2]:
t = tf.constant([[1., 2. ,3.], [4., 5. ,6.]])

In [3]:
# index
print(t)
print(t[:, 1:])

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [4]:
# op
print( t + 10)
print(tf.square(t))
print(t @  tf.transpose(t))

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


> 在tf1中，只有创建了一个session后才能进行print

In [5]:
# numpy
print(t.numpy())
print(tf.constant(np.array([1, 2, 3])))

[[1. 2. 3.]
 [4. 5. 6.]]
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [6]:
# Scalars 0维的tensor
t = tf.constant(3.1415)
print(t.numpy(), t.shape)

3.1415 ()


**字符串常量**`tf.strings`

In [7]:
t = tf.constant('like')
print(t)

tf.Tensor(b'like', shape=(), dtype=string)


In [8]:
print(tf.strings.length(t))
print(tf.strings.length(t, unit='UTF8_CHAR')) # utf-8编码长度

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [9]:
# string array
t = tf.constant(['cafe', 'like', '牛奶'])
print(tf.strings.length(t, unit='UTF8_CHAR'))
r = tf.strings.unicode_decode(t, 'UTF8')
print(r)

tf.Tensor([4 4 2], shape=(3,), dtype=int32)
<tf.RaggedTensor [[99, 97, 102, 101], [108, 105, 107, 101], [29275, 22902]]>


**不规则tensor** `tf.ragged.constant`

In [10]:
r = tf.ragged.constant([[11., 2., 3.], [1., 5. ]])
print(r)

<tf.RaggedTensor [[11.0, 2.0, 3.0], [1.0, 5.0]]>


In [11]:
# index
print(r[1])
print(r[1:2])

tf.Tensor([1. 5.], shape=(2,), dtype=float32)
<tf.RaggedTensor [[1.0, 5.0]]>


In [12]:
# ops
r2 = tf.ragged.constant([[1., 4.], [3.]])
print(tf.concat([r, r2], axis=0))

<tf.RaggedTensor [[11.0, 2.0, 3.0], [1.0, 5.0], [1.0, 4.0], [3.0]]>


In [13]:
print(r.to_tensor())

tf.Tensor(
[[11.  2.  3.]
 [ 1.  5.  0.]], shape=(2, 3), dtype=float32)


**稀疏矩阵**`tf.SparseTensor`

In [14]:
s = tf.SparseTensor(indices = [[0, 1], [1, 0], [2, 3]], 
                    values = [2, 3, 1],
                    dense_shape = [3, 4]) # 非0位置的索引， 非0位置的值， 矩阵的形状
print(s)
print(tf.sparse.to_dense(s))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2 3 1], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0 2 0 0]
 [3 0 0 0]
 [0 0 0 1]], shape=(3, 4), dtype=int32)


In [15]:
# ops
s2 = s * 2
print(s2)
s4 = tf.constant(np.random.randint(1,  4, (4, 3)))
print(tf.sparse.sparse_dense_matmul(s, s4))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([4 6 2], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[4 4 4]
 [9 9 9]
 [3 3 1]], shape=(3, 3), dtype=int32)


> 稀疏矩阵不能进行加法

**变量**`tf.Variable`

In [16]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
print(v)
print(v.value())
print(v.numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
[[1. 2. 3.]
 [4. 5. 6.]]


In [17]:
# reassign
v.assign(2 * v)
print(v)
v[0, 1].assign(42)
print(v)
v[1].assign([1., 8., 9.])
print(v)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 1.,  8.,  9.]], dtype=float32)>


> 变量不能使用=重新赋值

## **1.2 函数api(后续补充)**